### ISSUE TITLE
Feat: File I/O 및 CGI 처리를 담당하는 클래스 생성

### ISSUE THREAD

**Issue by PIut0** [PIut0/Webserv#11]
# TODO
- [x] Sock 클래스명을 FdInterface 로 변경
- [ ] FdInterface 를 상속받는 Cgi 클래스 생성
- [x] FdInterface 를 상속받는 FileIO 클래스 생성
