### ISSUE TITLE
Refactor : check code convention

### ISSUE THREAD

**Issue by rkskekzzz** [PIut0/Webserv#121]
# TODO

- [x] class public -> protected -> private 순서
- [x] 복사생성자, 대입연산자 헤더에서 파라미터 명 제거
- [x] switch-case 문 indent 수정(switch 1탭, case 2탭)
- [x] 변수명 컨벤션 통일(ex. lowerCamelCase, privateValue_)
- [x] 함수명 컨벤션 통일(ex, NoUnderLineInFunction(int type) )
- [x] void 함수 불필요한 return 제거
