### ISSUE TITLE
Refactor: test file 정리

### ISSUE THREAD

**Issue by rkskekzzz** [PIut0/Webserv#46]
# TODO

코드 제거 후 푸시 전, workflow 수정 먼저 할 것

- [x] test_http_header.cpp 제거
- [x] test_string_ref_ref 제거
- [x] test_get, post, put, delete 생성
- [x] test_locationblock_class와 test_serverblock_class로 나눠서 다시 생성
